"""move is_settled from Valuations to Trades

Revision ID: 952f21b33873
Revises: af52d867a9d7
Create Date: 2026-08-27 23:02:04.530980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952f21b33873'
down_revision: Union[str, Sequence[str], None] = 'af52d867a9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trades', sa.Column('is_settled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('Trades', 'is_settled', server_default=None)
    op.drop_column('Valuations', 'is_settled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Valuations', sa.Column('is_settled', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))
    op.alter_column('Valuations', 'is_settled', server_default=None)
    op.drop_column('Trades', 'is_settled')
    # ### end Alembic commands ###
