"""add is_settled in Valuations

Revision ID: af52d867a9d7
Revises: ffe77487b4cc
Create Date: 2026-08-27 22:56:17.468479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af52d867a9d7'
down_revision: Union[str, Sequence[str], None] = 'ffe77487b4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Valuations', sa.Column('is_settled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('Valuations', 'is_settled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Valuations', 'is_settled')
    # ### end Alembic commands ###
