"""initial migration

Revision ID: ffe77487b4cc
Revises: 
Create Date: 2026-07-28 17:21:36.334209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffe77487b4cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditLogs',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('Books',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_asset_class', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('MarketDataCurves',
    sa.Column('curve_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('curve_name', sa.Text(), nullable=False),
    sa.Column('curve_type', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('tenors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('curve_id')
    )
    op.create_table('MarketDataSnapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_type', sa.Text(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('MarketDataSpotPrices',
    sa.Column('market_data_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('ask', sa.Numeric(), nullable=True),
    sa.Column('mid', sa.Numeric(), nullable=True),
    sa.Column('last', sa.Numeric(), nullable=True),
    sa.Column('spot', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('market_data_id')
    )
    op.create_table('Trades',
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('instrument_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('trade_price', sa.Numeric(), nullable=False),
    sa.Column('trade_currency', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('client_request_id', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Books.book_id'], ),
    sa.PrimaryKeyConstraint('trade_id'),
    sa.UniqueConstraint('client_request_id')
    )
    op.create_table('Valuations',
    sa.Column('valuation_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('valuation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fair_value', sa.Numeric(), nullable=False),
    sa.Column('market_value', sa.Numeric(), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=False),
    sa.Column('total_pnl', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('market_data_reference', sa.Text(), nullable=True),
    sa.Column('valuation_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Books.book_id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['Trades.trade_id'], ),
    sa.PrimaryKeyConstraint('valuation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Valuations')
    op.drop_table('Trades')
    op.drop_table('MarketDataSpotPrices')
    op.drop_table('MarketDataSnapshots')
    op.drop_table('MarketDataCurves')
    op.drop_table('Books')
    op.drop_table('AuditLogs')
    # ### end Alembic commands ###
